[package]
name = "rnlib"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# For now use vendored path
gdnative = { path = "../godot-rust/gdnative" }
rand = "*"

# RUST_BACKTRACE=1 cargo watch -x build --clear
