[package]
name = "geo-clip"
version = "0.1.0"
authors = ["Fabian Keller <github.100.fkeller@spamgourmet.com>"]
edition = "2018"

[dependencies]

# geo-types = { version = "0.4", default-features = false }
geo-types = "0.4"
geo = "*"

